### ISSUE TITLE
Raspberry Pi Install ? 

### ISSUE THREAD

**Issue by Write** [martinbjeldbak/acestream-http-proxy#13]
Hello, all acestream versions for Linux seems to be for AMD64 : https://docs.acestream.net/products/#linux
Is there a way to run it on Raspberry Pi (ARM64) then ? 

Thanks

**Comment by martinbjeldbak** [comment]
Hi @Write not at this stage as far as I'm aware. Relates to #5 which is regarding running AceStream on ARM-based Macbooks. You can try the workaround posted in the comment here https://github.com/martinbjeldbak/acestream-http-proxy/issues/5#issuecomment-1657122111

Let me know how you go!

**Comment by Write** [comment]
> Hi @Write not at this stage as far as I'm aware. Relates to #5 which is regarding running AceStream on ARM-based Macbooks. You can try the workaround posted in the comment here [#5 (comment)](https://github.com/martinbjeldbak/acestream-http-proxy/issues/5#issuecomment-1657122111)
> 
> Let me know how you go!

I tried it, but it didn't work back then, unfortunately.
I've found an older docker-compose from another repo, with binaries included, which seems that was back when Acestream still produced arm64 build. (or someone reverse engineered it, idk); 

The only issue is that it reboot the container each time the stream is stopped.

Still a great workaround if anyone really needs it.
Repo : https://github.com/danielchc/docker-acestream-arm

My docker-compose.yml

```
version: '3'
services:
  acestream:
    image: danielchc/acestream-arm:latest
    container_name: acestream
    hostname: acestream
    ports:
      - '6878:6878'
      - '8621:8621'
    restart: always
```
