### ISSUE TITLE
deny access error on remote server

### ISSUE THREAD

**Issue by iercan** [martinbjeldbak/acestream-http-proxy#22]
I've installed the application locally and it works fine, but when I attempt to deploy it on a remote VPS, I encounter the following error. I don't have any firewall rules that might block requests. What could be the reason?

```
app-1  | 2024-05-15 07:22:25,749|Thread-45|acestream.httpserver|deny access from ('xxx.xxx.xxx.xxx', 47642)
app-1  | 2024-05-15 07:22:25,873|Thread-46|acestream.httpserver|deny access from ('xxx.xxx.xxx.xxx', 48660)
```

**Comment by iercan** [comment]
I discovered the issue: remote access was disabled by default. After enabling it, everything worked.

https://docs.acestream.net/developers/api-reference/#set_allow_remote_access

**Comment by julioplz** [comment]
Can you explain how to enable it, please?

**Comment by iercan** [comment]
@julioplz 

The information is detailed in the link I provided.

First, obtain an access token for public access:

`$ curl "http://127.0.0.1:6878/server/api?api_version=3&method=get_api_access_token"`

Then use this token to enable remote access:

`$ curl "http://127.0.0.1:6878/server/api?api_version=3&method=set_allow_intranet_access&token=3c3a67a7048cfa2e2097b2a5491c57121e39ab496f4b7b72d947088a87752a99&value=1"`

**Comment by iercan** [comment]
@Sergiomg86 
Ensure you use the localhost address and provide the token correctly. I can't think of any other reason for this issue.

**Comment by julioplz** [comment]
I have same issue and I'm running the container without docker-compose.

**Comment by iercan** [comment]
I suggest you check application logs. Tomorrow I will test it myself

**Comment by iercan** [comment]
@Sergiomg86
I understand the issue you are facing. Since you are running in a docker container, you need to execute the curl command within the container. Running it on the host machine is technically attempting to access remotely. The curl package is not pre-installed on the image; you can install it using the command provided below.

```
docker run -it  <your conaienr name> bash
apt update
apt install curl 
```

After this follow the insructions above "in the container".

**Comment by iercan** [comment]
@Sergiomg86 

Which os you are running? You should be able to use localhost addresses in container. 

Alternatively you can run it on host network. Use below compose file. Use port 80 instead of 6878. 

```
version: '3.9'
services:
  acestream:
    image: martinbjeldbak/acestream-http-proxy:latest
    container_name: acestream
    network_mode: host
    volumes:
      - /appdata/acestream:/root/.ACEStream
      - /appdata/acestream/by-id/:/dev/disk/by-id/
    environment:
      - PYTHONIOENCODING=utf-8
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    restart: unless-stopped
```
