### ISSUE TITLE
Acestream+warp docker-compose config

### ISSUE THREAD

**Issue by julioplz** [martinbjeldbak/acestream-http-proxy#38]
Hi. Anybody can provide a docker-compose config that combines acestream with free warp VPN for better privacy, please?
I don't have enough programming skills to achieve it. Thank you in advance.

**Comment by juhacz** [comment]
Run docker container with warp, add to acestream docker compose:
```
environment:
      - HTTP_PROXY=http://192.168.100.130:9091
```

where 9091 is port with warp container.

**Comment by julioplz** [comment]
Thank you very much

**Comment by julioplz** [comment]
I believe this config works fine:

```dockerfile
version: "3"

services:
  warp:
    image: caomingjun/warp
    container_name: warp
    restart: always
    # add removed rule back (https://github.com/opencontainers/runc/pull/3468)
    device_cgroup_rules:
      - 'c 10:200 rwm'
    ports:
      - "1080:1080"
    environment:
      - WARP_SLEEP=2
      # - WARP_LICENSE_KEY= # optional
      # - WARP_ENABLE_NAT=1 # enable nat
    cap_add:
      # Docker already have them, these are for podman users
      - MKNOD
      - AUDIT_WRITE
      # additional required cap for warp, both for podman and docker
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
      # uncomment for nat
      # - net.ipv4.ip_forward=1
      # - net.ipv6.conf.all.forwarding=1
      # - net.ipv6.conf.all.accept_ra=2
    volumes:
      - ./data:/var/lib/cloudflare-warp


  acestream-http-proxy:
    image: ghcr.io/martinbjeldbak/acestream-http-proxy
    container_name: acestream
    ports:
      - '6878:6878'
    environment:
      - ALLOW_REMOTE_ACCESS=yes # change to "yes" to allow internet access
      - HTTP_PROXY=http://warp:1080
     # add any extra command line option mentioned in https://docs.acestream.net/developers/engine-command-line-options
     # - EXTRA_FLAGS='' 
```

**Comment by juhacz** [comment]
My stacks

```
name: warp
services:
    docker-warp-socks:
        restart: always
        stdin_open: true
        tty: true
        container_name: warp_socks_plus
        environment:
            - WARP_LICENSE=$WARP_LICENSE
            - NET_PORT=9091
        ports:
            - 9091:9091
        image: monius/docker-warp-socks:v3
        
```

```
services:
  acestream6878:
    image: smarquezp/docker-acestream-ubuntu-home:latest
    ports:
      - 6878:6878
    environment:
      - HTTP_PROXY=http://192.168.100.130:9091
      - HTTPS_PROXY=http://192.168.100.130:9091
      - TZ=Europe/Warsaw
      - INTERNAL_IP=127.0.0.1
      - HTTP_PORT=6878
      - HTTPS_PORT=6879
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    restart: always

```
